# Generated by Django 4.2.13 on 2024-05-12 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvetime', models.IntegerField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('solved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
