# Generated by Django 4.2.13 on 2024-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubetimer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
