# Generated by Django 4.2.13 on 2024-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubetimer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='solvetime',
            field=models.IntegerField(),
        ),
    ]
