# Generated by Django 4.2.13 on 2024-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubetimer_app', '0002_alter_solve_solvetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='solvetime',
            field=models.FloatField(),
        ),
    ]
